version: '3.8'
services:
  web:
    container_name: 'blogwebfrontend'
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: 'backendnodejs'
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=omnagare
      - PORT=3000
      - MONGODBURL=mongodb://db:27017/newblog
    depends_on:
      - db
  

  db:
    container_name: 'db'
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
