apiVersion: 'apps/v1'
kind: Deployment
metadata:
  name: container
  labels:
    app: blogwebdeployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: blogwebdeployment
  template:
    metadata: 
      labels:
        app: blogwebdeployment
    spec: 
      containers:
        - name: my-container
          image: omnagare/blogwebodm:latest
          ports:
            - containerPort: 8080
          env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: blogodm-secret
                key: JWT_SECRET
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: blogodm-config
                key: PORT
          - name: MONGODBURL
            valueFrom:
              configMapKeyRef:
                name: blogodm-config
                key: MONGODBURL

---

apiVersion: 'v1'
kind: Service
metadata:
  name: exposeblog
spec:
  type: LoadBalancer
  selector:
    app: blogwebdeployment
  ports:
    - port: 8080
      targetPort: 8080

